/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-2px)" },
        },
        wobble: {
          "0%, 100%": { transform: "rotate(0deg)" },
          "25%": { transform: "rotate(-2deg)" },
          "75%": { transform: "rotate(2deg)" },
        },
        shake: {
          "0%, 100%": { transform: "translateX(0)" },
          "25%": { transform: "translateX(-4px)" },
          "75%": { transform: "translateX(4px)" },
        },
        success: {
          "0%": { backgroundColor: "hsl(var(--success))", opacity: "1" },
          "100%": { backgroundColor: "transparent", opacity: "0" },
        },
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        float: "float 3s ease-in-out infinite",
        wobble: "wobble 0.3s ease-in-out",
        shake: "shake 0.3s ease-in-out",
        success: "success 0.4s ease-out",
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    themes: [
      {
        quartiles: {
          primary: "#5B7B6F",
          "primary-content": "#FFFFFF",
          secondary: "#8B7355",
          "secondary-content": "#FFFFFF",
          accent: "#C4A484",
          "accent-content": "#1F1F1F",
          neutral: "#3D3D3D",
          "neutral-content": "#F5F2EB",
          "base-100": "#FAF8F5",
          "base-200": "#F0EDE6",
          "base-300": "#E5E0D5",
          "base-content": "#2D2D2D",
          info: "#6B9AC4",
          success: "#7BAE7F",
          warning: "#D4A574",
          error: "#C47B7B",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.75rem",
          "--rounded-badge": "1rem",
          "--animation-btn": "0.2s",
          "--animation-input": "0.2s",
          "--btn-focus-scale": "0.98",
          "--border-color": "#E5E0D5",
          "--ring-offset": "2px",
          "--ring-color": "rgba(91, 123, 111, 0.3)",
        },
      },
      {
        "quartiles-dark": {
          primary: "#7B9B8F",
          "primary-content": "#1A1A1A",
          secondary: "#AB9375",
          "secondary-content": "#1A1A1A",
          accent: "#D4B494",
          "accent-content": "#1A1A1A",
          neutral: "#9D9D9D",
          "neutral-content": "#1A1A1A",
          "base-100": "#1A1917",
          "base-200": "#252420",
          "base-300": "#302E28",
          "base-content": "#E8E4DC",
          info: "#8BBAE4",
          success: "#9BCE9F",
          warning: "#E4C594",
          error: "#E49B9B",
          "--rounded-box": "1rem",
          "--rounded-btn": "0.75rem",
          "--rounded-badge": "1rem",
          "--animation-btn": "0.2s",
          "--animation-input": "0.2s",
          "--btn-focus-scale": "0.98",
          "--border-color": "#302E28",
          "--ring-offset": "2px",
          "--ring-color": "rgba(123, 155, 143, 0.3)",
        },
      },
    ],
    darkTheme: "quartiles-dark",
  },
}
