// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const GameStartRequestSchema = {
    properties: {
        device_fingerprint: {
            type: 'string',
            title: 'Device Fingerprint'
        },
        player_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Player Id'
        }
    },
    type: 'object',
    required: ['device_fingerprint'],
    title: 'GameStartRequest',
    description: 'Request to start a new game session.'
} as const;

export const GameStartResponseSchema = {
    properties: {
        session_id: {
            type: 'string',
            title: 'Session Id'
        },
        player_id: {
            type: 'string',
            title: 'Player Id'
        },
        display_name: {
            type: 'string',
            title: 'Display Name'
        },
        tiles: {
            items: {
                '$ref': '#/components/schemas/TileSchema'
            },
            type: 'array',
            title: 'Tiles'
        },
        already_played: {
            type: 'boolean',
            title: 'Already Played'
        },
        previous_result: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PreviousResultSchema'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['session_id', 'player_id', 'display_name', 'tiles', 'already_played'],
    title: 'GameStartResponse',
    description: 'Response when starting a new game.'
} as const;

export const GameSubmitResponseSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        final_score: {
            type: 'integer',
            title: 'Final Score'
        },
        solve_time_ms: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Solve Time Ms'
        },
        leaderboard_rank: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Leaderboard Rank'
        },
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['success', 'final_score', 'message'],
    title: 'GameSubmitResponse',
    description: 'Response after submitting/finalizing a game.'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HintResponseSchema = {
    properties: {
        hint_number: {
            type: 'integer',
            title: 'Hint Number'
        },
        definition: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Definition'
        },
        time_penalty_ms: {
            type: 'integer',
            title: 'Time Penalty Ms'
        },
        quartiles_remaining: {
            type: 'integer',
            title: 'Quartiles Remaining'
        }
    },
    type: 'object',
    required: ['hint_number', 'time_penalty_ms', 'quartiles_remaining'],
    title: 'HintResponse',
    description: 'Response after requesting a hint.'
} as const;

export const LeaderboardEntrySchemaSchema = {
    properties: {
        rank: {
            type: 'integer',
            title: 'Rank'
        },
        player_id: {
            type: 'string',
            title: 'Player Id'
        },
        display_name: {
            type: 'string',
            title: 'Display Name'
        },
        solve_time_ms: {
            type: 'integer',
            title: 'Solve Time Ms'
        }
    },
    type: 'object',
    required: ['rank', 'player_id', 'display_name', 'solve_time_ms'],
    title: 'LeaderboardEntrySchema',
    description: 'A single leaderboard entry.'
} as const;

export const LeaderboardResponseSchema = {
    properties: {
        puzzle_id: {
            type: 'string',
            title: 'Puzzle Id'
        },
        puzzle_date: {
            type: 'string',
            format: 'date',
            title: 'Puzzle Date'
        },
        entries: {
            items: {
                '$ref': '#/components/schemas/LeaderboardEntrySchema'
            },
            type: 'array',
            title: 'Entries'
        },
        total_entries: {
            type: 'integer',
            title: 'Total Entries'
        },
        player_rank: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Player Rank'
        }
    },
    type: 'object',
    required: ['puzzle_id', 'puzzle_date', 'entries', 'total_entries'],
    title: 'LeaderboardResponse',
    description: 'Leaderboard data for a puzzle.'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message',
    description: 'Generic message response.'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword',
    description: 'Schema for password reset with token.'
} as const;

export const PreviousResultSchemaSchema = {
    properties: {
        final_score: {
            type: 'integer',
            title: 'Final Score'
        },
        solve_time_ms: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Solve Time Ms'
        },
        words_found: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Words Found'
        },
        leaderboard_rank: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Leaderboard Rank'
        }
    },
    type: 'object',
    required: ['final_score', 'words_found'],
    title: 'PreviousResultSchema',
    description: 'Result from a previous game session.'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate',
    description: 'Schema for creating a user via private API.'
} as const;

export const PuzzleResponseSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        date: {
            type: 'string',
            format: 'date',
            title: 'Date'
        },
        tiles: {
            items: {
                '$ref': '#/components/schemas/TileSchema'
            },
            type: 'array',
            title: 'Tiles'
        },
        total_available_points: {
            type: 'integer',
            title: 'Total Available Points'
        }
    },
    type: 'object',
    required: ['id', 'date', 'tiles', 'total_available_points'],
    title: 'PuzzleResponse',
    description: 'Puzzle data returned to client.'
} as const;

export const TileSchemaSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        letters: {
            type: 'string',
            title: 'Letters'
        }
    },
    type: 'object',
    required: ['id', 'letters'],
    title: 'TileSchema',
    description: 'A single tile in the puzzle grid.'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token',
    description: 'OAuth2 token response.'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword',
    description: 'Schema for password update request.'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate',
    description: 'Schema for creating a new user.'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic',
    description: 'Public user information returned by API.'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister',
    description: 'Schema for user self-registration.'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate',
    description: 'Schema for updating a user (admin).'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe',
    description: 'Schema for users updating their own information.'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic',
    description: 'List of public user information with pagination count.'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const WordValidationRequestSchema = {
    properties: {
        word: {
            type: 'string',
            title: 'Word'
        }
    },
    type: 'object',
    required: ['word'],
    title: 'WordValidationRequest',
    description: 'Request to validate a submitted word.'
} as const;

export const WordValidationResponseSchema = {
    properties: {
        is_valid: {
            type: 'boolean',
            title: 'Is Valid'
        },
        points: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Points'
        },
        reason: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reason'
        },
        is_quartile: {
            type: 'boolean',
            title: 'Is Quartile',
            default: false
        },
        current_score: {
            type: 'integer',
            title: 'Current Score'
        },
        is_solved: {
            type: 'boolean',
            title: 'Is Solved'
        }
    },
    type: 'object',
    required: ['is_valid', 'current_score', 'is_solved'],
    title: 'WordValidationResponse',
    description: 'Response after validating a word.'
} as const;