// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * Request to start a new game session.
 */
export type GameStartRequest = {
    device_fingerprint: string;
    player_id?: (string | null);
};

/**
 * Response when starting a new game.
 */
export type GameStartResponse = {
    session_id: string;
    player_id: string;
    display_name: string;
    tiles: Array<TileSchema>;
    already_played: boolean;
    previous_result?: (PreviousResultSchema | null);
};

/**
 * Response after submitting/finalizing a game.
 */
export type GameSubmitResponse = {
    success: boolean;
    final_score: number;
    solve_time_ms?: (number | null);
    leaderboard_rank?: (number | null);
    message: string;
};

/**
 * Response after requesting a hint.
 */
export type HintResponse = {
    hint_number: number;
    definition?: (string | null);
    time_penalty_ms: number;
    quartiles_remaining: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * A single leaderboard entry.
 */
export type LeaderboardEntrySchema = {
    rank: number;
    player_id: string;
    display_name: string;
    solve_time_ms: number;
};

/**
 * Leaderboard data for a puzzle.
 */
export type LeaderboardResponse = {
    puzzle_id: string;
    puzzle_date: string;
    entries: Array<LeaderboardEntrySchema>;
    total_entries: number;
    player_rank?: (number | null);
};

/**
 * Generic message response.
 */
export type Message = {
    message: string;
};

/**
 * Schema for password reset with token.
 */
export type NewPassword = {
    token: string;
    new_password: string;
};

/**
 * Result from a previous game session.
 */
export type PreviousResultSchema = {
    final_score: number;
    solve_time_ms?: (number | null);
    words_found: Array<(string)>;
    leaderboard_rank?: (number | null);
};

/**
 * Schema for creating a user via private API.
 */
export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

/**
 * Puzzle data returned to client.
 */
export type PuzzleResponse = {
    id: string;
    date: string;
    tiles: Array<TileSchema>;
    total_available_points: number;
};

/**
 * A single tile in the puzzle grid.
 */
export type TileSchema = {
    id: number;
    letters: string;
};

/**
 * OAuth2 token response.
 */
export type Token = {
    access_token: string;
    token_type?: string;
};

/**
 * Schema for password update request.
 */
export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

/**
 * Schema for creating a new user.
 */
export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

/**
 * Public user information returned by API.
 */
export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

/**
 * Schema for user self-registration.
 */
export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

/**
 * List of public user information with pagination count.
 */
export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

/**
 * Schema for updating a user (admin).
 */
export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

/**
 * Schema for users updating their own information.
 */
export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

/**
 * Request to validate a submitted word.
 */
export type WordValidationRequest = {
    word: string;
};

/**
 * Response after validating a word.
 */
export type WordValidationResponse = {
    is_valid: boolean;
    points?: (number | null);
    reason?: (string | null);
    is_quartile?: boolean;
    current_score: number;
    is_solved: boolean;
};

export type GameStartGameData = {
    requestBody: GameStartRequest;
};

export type GameStartGameResponse = (GameStartResponse);

export type GameValidateWordData = {
    requestBody: WordValidationRequest;
    sessionId: string;
};

export type GameValidateWordResponse = (WordValidationResponse);

export type GameSubmitGameData = {
    sessionId: string;
};

export type GameSubmitGameResponse = (GameSubmitResponse);

export type GameGetHintData = {
    sessionId: string;
};

export type GameGetHintResponse = (HintResponse);

export type LeaderboardGetTodaysLeaderboardData = {
    limit?: number;
    playerId?: (string | null);
};

export type LeaderboardGetTodaysLeaderboardResponse = (LeaderboardResponse);

export type LeaderboardGetLeaderboardByDateData = {
    leaderboardDate: string;
    limit?: number;
    playerId?: (string | null);
};

export type LeaderboardGetLeaderboardByDateResponse = (LeaderboardResponse);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type PuzzleGetTodaysPuzzleResponse = (PuzzleResponse);

export type PuzzleGetPuzzleByDateData = {
    puzzleDate: string;
};

export type PuzzleGetPuzzleByDateResponse = (PuzzleResponse);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);