"""Player name generation service."""

import random

ADJECTIVES = [
    "Chubby",
    "Sleepy",
    "Grumpy",
    "Happy",
    "Sneaky",
    "Fluffy",
    "Bouncy",
    "Wobbly",
    "Jazzy",
    "Cozy",
    "Mighty",
    "Tiny",
    "Rotund",
    "Peppy",
    "Mellow",
    "Zesty",
    "Quirky",
    "Dapper",
    "Plucky",
    "Snappy",
    "Breezy",
    "Crispy",
    "Dizzy",
    "Frosty",
    "Giddy",
    "Hasty",
    "Icy",
    "Jolly",
    "Kooky",
    "Lively",
    "Merry",
    "Nifty",
    "Perky",
    "Rusty",
    "Sassy",
    "Toasty",
    "Wacky",
    "Zippy",
    "Chunky",
    "Funky",
    "Groovy",
    "Lumpy",
    "Murky",
    "Nutty",
    "Pudgy",
    "Quirky",
    "Spunky",
    "Swanky",
    "Tacky",
    "Yucky",
    "Zany",
    "Bumpy",
    "Dusty",
    "Foggy",
    "Gloomy",
    "Hazy",
    "Icky",
    "Jumpy",
    "Lucky",
    "Messy",
    "Noisy",
    "Picky",
    "Rocky",
    "Salty",
    "Tricky",
    "Windy",
    "Brainy",
    "Clumsy",
    "Dreamy",
    "Feisty",
    "Grouchy",
    "Hangry",
    "Itchy",
    "Jittery",
    "Lanky",
    "Moody",
    "Nerdy",
    "Peppy",
    "Rowdy",
    "Snooty",
    "Testy",
    "Woozy",
    "Yappy",
    "Zonked",
    "Antsy",
    "Bushy",
    "Cranky",
    "Dopey",
    "Edgy",
    "Fizzy",
    "Gassy",
    "Huffy",
    "Inky",
    "Jerky",
    "Kinky",
    "Loopy",
]

NOUNS = [
    "Penguin",
    "Unicorn",
    "Mango",
    "Pancake",
    "Walrus",
    "Hedgehog",
    "Narwhal",
    "Cupcake",
    "Platypus",
    "Turnip",
    "Koala",
    "Avocado",
    "Badger",
    "Biscuit",
    "Cactus",
    "Dolphin",
    "Falcon",
    "Gopher",
    "Hamster",
    "Iguana",
    "Jackal",
    "Kitten",
    "Lemur",
    "Moose",
    "Newt",
    "Otter",
    "Panda",
    "Quail",
    "Rabbit",
    "Salmon",
    "Turtle",
    "Vulture",
    "Wombat",
    "Yak",
    "Zebra",
    "Alpaca",
    "Beaver",
    "Clam",
    "Donkey",
    "Emu",
    "Ferret",
    "Goose",
    "Hippo",
    "Ibis",
    "Jellyfish",
    "Kangaroo",
    "Llama",
    "Meerkat",
    "Numbat",
    "Octopus",
    "Parrot",
    "Quokka",
    "Raccoon",
    "Seal",
    "Toucan",
    "Urchin",
    "Viper",
    "Walnut",
    "Yeti",
    "Zucchini",
    "Acorn",
    "Bagel",
    "Carrot",
    "Donut",
    "Eclair",
    "Falafel",
    "Gumball",
    "Hotdog",
    "Icecream",
    "Jelly",
    "Kiwi",
    "Lemon",
    "Muffin",
    "Nugget",
    "Olive",
    "Pickle",
    "Quinoa",
    "Raisin",
    "Sushi",
    "Taco",
    "Udon",
    "Waffle",
    "Yogurt",
    "Ziti",
    "Asteroid",
    "Blizzard",
    "Comet",
    "Doodle",
    "Eclipse",
    "Firefly",
    "Galaxy",
    "Hurricane",
    "Icicle",
    "Jumble",
    "Kazoo",
    "Lollipop",
]


def generate_player_name() -> str:
    """Generate a unique AdjectiveNoun player display name.

    Returns:
        A name like "ChubbyPenguin" or "SleepyMango"
    """
    adjective = random.choice(ADJECTIVES)
    noun = random.choice(NOUNS)
    return f"{adjective}{noun}"


def generate_unique_player_name(existing_names: set[str], max_attempts: int = 100) -> str | None:
    """Generate a player name that doesn't conflict with existing names.

    Args:
        existing_names: Set of names already in use
        max_attempts: Maximum generation attempts before returning None

    Returns:
        A unique name, or None if max_attempts exceeded
    """
    for _ in range(max_attempts):
        name = generate_player_name()
        if name not in existing_names:
            return name
    return None
